# Domain information
url: "https://life-echecs.org"
baseurl: ""

# Langugage
lang: "fr"
locale: "fr"

# Author
author:
  name: Jean Heibig
  email: jean@life-echecs.org

# Title and description
title: LIFE
tagline: Ligue Ingénieure Française d'Échecs
description: >
  Bienvenue sur le site de la Ligue Ingénieure Française d'Échecs !
  Nous organisons chaque année un tournoi d'échecs où les élèves d'écoles
  d'ingénieurs s'affrontent par équipes et tentent de remporter des prix
  prestigieux pour leur école.

# Theme https://www.csrhymes.com/bulma-clean-theme/
remote_theme: chrisrhymes/bulma-clean-theme
theme_color: "#e5e1f2"

# Plugins
plugins:
 - jekyll-seo-tag  # Meta

# Navigation
fixed_navbar: top
footer_menu: footer_menu

# Google
google_analytics: UA-237400932-1

