description: Ligue Ingénieure Française d'échecs
# google_analytics:
show_downloads: true
title: LIFE
theme: jekyll-theme-cayman
url: http://life-echecs.org

collections_dir: collections
collections:
  - sponsors